arm bicep e2e v2

diff --git a/.github/workflows/arm-bicep-e2e-v2.yaml b/.github/workflows/arm-bicep-e2e-v2.yaml
--- a/.github/workflows/arm-bicep-e2e-v2.yaml
+++ b/.github/workflows/arm-bicep-e2e-v2.yaml
@@ -67,14 +67,14 @@ jobs:
       - name: 🧪 Run ARM Bicep E2E Tests
         run: task teste2e:armbicep
 
-      - name: 📤 Upload ARM Bicep e2e test coverage file
-        if: always()
-        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
-        with:
-          name: ${{ format('{0}-{1}-test-coverage-file', matrix.cli, env.CLI_VERSION) }}
-          path: coverage.out
-          if-no-files-found: warn
-          overwrite: true
+      # - name: 📤 Upload ARM Bicep e2e test coverage file
+      #   if: always()
+      #   uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
+      #   with:
+      #     name: ${{ format('{0}-{1}-test-coverage-file', matrix.cli, env.CLI_VERSION) }}
+      #     path: coverage.out
+      #     if-no-files-found: warn
+      #     overwrite: true
 
       # - name: 📤 Upload ARM Bicep e2e test results
       #   if: always()
@@ -85,62 +85,62 @@ jobs:
       #     if-no-files-found: warn
       #     overwrite: true
 
-      - name: 📤 Upload ARM Bicep e2e test coverage results
-        if: always()
-        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
-        with:
-          name: ${{ format('{0}-{1}-test-coverage-results', matrix.cli, env.CLI_VERSION) }}
-          path: |
-            coverage.html
-            coverage.json
-            coverage.out
-            coverage.txt
-            coverage.xml
-          if-no-files-found: warn
-          overwrite: true
+  #     - name: 📤 Upload ARM Bicep e2e test coverage results
+  #       if: always()
+  #       uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
+  #       with:
+  #         name: ${{ format('{0}-{1}-test-coverage-results', matrix.cli, env.CLI_VERSION) }}
+  #         path: |
+  #           coverage.html
+  #           coverage.json
+  #           coverage.out
+  #           coverage.txt
+  #           coverage.xml
+  #         if-no-files-found: warn
+  #         overwrite: true
 
-      - name: 📢 Publish ARM Bicep e2e test results
-        if: always()
-        uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1.9.1
-        with:
-          name: 📜 Test results (${{ matrix.cli }} ${{ matrix.version }})
-          reporter: jest-junit
-          path: testresults.xml
-          token: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: 📢 Publish ARM Bicep e2e test results
+  #       if: always()
+  #       uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1.9.1
+  #       with:
+  #         name: 📜 Test results (${{ matrix.cli }} ${{ matrix.version }})
+  #         reporter: jest-junit
+  #         path: testresults.xml
+  #         token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: ⚙️ Get ARM Bicep e2e test Coverage summary
-        if: always()
-        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
-        with:
-          filename: coverage.xml
-          badge: true
-          fail_below_min: true
-          format: markdown
-          hide_branch_rate: false
-          hide_complexity: false
-          indicators: true
-          output: both
-          thresholds: "30 60"
+  #     - name: ⚙️ Get ARM Bicep e2e test Coverage summary
+  #       if: always()
+  #       uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
+  #       with:
+  #         filename: coverage.xml
+  #         badge: true
+  #         fail_below_min: true
+  #         format: markdown
+  #         hide_branch_rate: false
+  #         hide_complexity: false
+  #         indicators: true
+  #         output: both
+  #         thresholds: "30 60"
 
-      - name: 📤 Upload ARM Bicep e2e Coverage summary
-        if: always()
-        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
-        with:
-          name: ${{ format('{0}-{1}-test-coverage-summary', matrix.cli, env.CLI_VERSION) }}
-          path: |
-            code-coverage-results.md
-          if-no-files-found: warn
-          overwrite: true
+  #     - name: 📤 Upload ARM Bicep e2e Coverage summary
+  #       if: always()
+  #       uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
+  #       with:
+  #         name: ${{ format('{0}-{1}-test-coverage-summary', matrix.cli, env.CLI_VERSION) }}
+  #         path: |
+  #           code-coverage-results.md
+  #         if-no-files-found: warn
+  #         overwrite: true
   
-  check-test-matrix:
-    if: always()
-    name: 🧪 Check ARM Bicep e2e Tests
-    needs: testarmbicepe2e
-    runs-on: ubuntu-24.04
-    steps:
-      - name: ✅ OK
-        if: ${{ !(contains(needs.*.result, 'failure')) }}
-        run: exit 0
-      - name: 🛑 Failure
-        if: ${{ contains(needs.*.result, 'failure') }}
-        run: exit 1
+  # check-test-matrix:
+  #   if: always()
+  #   name: 🧪 Check ARM Bicep e2e Tests
+  #   needs: testarmbicepe2e
+  #   runs-on: ubuntu-24.04
+  #   steps:
+  #     - name: ✅ OK
+  #       if: ${{ !(contains(needs.*.result, 'failure')) }}
+  #       run: exit 0
+  #     - name: 🛑 Failure
+  #       if: ${{ contains(needs.*.result, 'failure') }}
+  #       run: exit 1
